include(${CMAKE_CURRENT_LIST_DIR}/Target/CortexM3.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Target/CortexM4.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Target/CortexM4F.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Target/CortexM7.cmake)

message("CFXS: Set core to ${CFXS_CORE}")
if(${CFXS_CORE} STREQUAL "Cortex_M3")
    CFXS_SetTarget_CortexM3(${PROJECT_NAME})
elseif(${CFXS_CORE} STREQUAL "Cortex-M4")
    CFXS_SetTarget_CortexM4(${PROJECT_NAME})
elseif(${CFXS_CORE} STREQUAL "Cortex-M4F")
    CFXS_SetTarget_CortexM4F(${PROJECT_NAME})
elseif(${CFXS_CORE} STREQUAL "Cortex-M7")
    CFXS_SetTarget_CortexM7(${PROJECT_NAME})
else()
    message(FATAL_ERROR "Unknown CFXS_CORE: [${CFXS_CORE}]")
endif()